[project]
name = "pathfinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "auditwheel>=6.4.1",
    "cibuildwheel>=3.0.1",
    "patchelf>=0.17.2.2",
    "pybind11>=3.0.0",
    "setuptools>=80.9.0",
    "twine>=6.1.0",
    "wheel>=0.45.1",
]
