name: Build Wheels
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          pybuilds: cp3{10,11,12}-manylinux_x86_64
          arch: x86_64
          id: linux_x86_64
        - os: macos-15
          pybuilds: cp3{10,11,12}-macosx_arm64
          arch: arm64
          id: macos_arm64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.1
        with:
          output-dir: wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.pybuilds }}
          CIBW_BEFORE_BUILD_MACOS: |
            brew update 
            brew install cmake boost eigen wget git
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg install octomap
            ./vcpkg/vcpkg install ompl
            unlink /Users/runner/work/path-finding/path-finding/vcpkg/packages/ompl_arm64-osx/debug/lib/libompl.dylib
            unlink /Users/runner/work/path-finding/path-finding/vcpkg/packages/ompl_arm64-osx/debug/lib/libompl.dylib.18
            cp /Users/runner/work/path-finding/path-finding/vcpkg/packages/ompl_arm64-osx/debug/lib/libompl.1.7.0.dylib /Users/runner/work/path-finding/path-finding/vcpkg/packages/ompl_arm64-osx/debug/lib/libompl.dylib
            cp /Users/runner/work/path-finding/path-finding/vcpkg/packages/ompl_arm64-osx/debug/lib/libompl.1.7.0.dylib /Users/runner/work/path-finding/path-finding/vcpkg/packages/ompl_arm64-osx/debug/lib/libompl.dylib.18

          CIBW_BEFORE_BUILD_LINUX: |
            yum install -y curl zip tar unzip epel-release cmake make gcc-c++ bzip2 wget git zip unzip tar perl-IPC-Cmd autoconf libtool intltool automake autoconf-archive gettext
            git clone https://github.com/microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg install octomap
            ./vcpkg/vcpkg install ompl
            unlink /project/vcpkg/packages/ompl_x64-linux/lib/libompl.so
            unlink /project/vcpkg/packages/ompl_x64-linux/lib/libompl.so.18
            cp /project/vcpkg/packages/ompl_x64-linux/lib/libompl.so.1.7.0 /project/vcpkg/packages/ompl_x64-linux/lib/libompl.so.18
            cp /project/vcpkg/packages/ompl_x64-linux/lib/libompl.so.1.7.0 /project/vcpkg/packages/ompl_x64-linux/lib/libompl.so.18

          CIBW_ENVIRONMENT_LINUX: CMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"
          CIBW_ENVIRONMENT_MACOS: CMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"
          CIBW_SKIP: "cp*-manylinux_i686 cp*-musllinux* cp*-win32" 

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: wheelhouse
