name: Build Wheels

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_wheels:
    runs-on: ubuntu-latest # This runner will host the cibuildwheel Docker containers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Note: vcpkg caching might be tricky with cibuildwheel's isolated environments.
      # For simplicity, vcpkg will be reinstalled within each build step.
      # Consider creating a custom cibuildwheel Docker image or exploring more advanced caching mechanisms that mount into the container if builds are too slow.

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip
          pip install scikit-build-core[pyproject] cibuildwheel setuptools wheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_SKIP: "pp* *-musllinux*" # Skip PyPy and musllinux builds
          CIBW_BUILD: "cp311-*"         # Only build for CPython 3.11
          
          # --- Environment variables for cibuildwheel's build environment ---
          # These commands run INSIDE the cibuildwheel Docker container (for Linux)
          # which typically uses a manylinux image (often CentOS-based, hence yum)
          # or on the macOS/Windows runner directly (if you add them to the matrix).

          # For Linux (manylinux) builds:
          CIBW_BEFORE_ALL_LINUX: >
            yum update -y &&
            yum install -y git autoconf automake libtool m4 pkgconfig cmake unzip curl tar zip perl-IPC-Cmd &&
            git clone https://github.com/microsoft/vcpkg.git /tmp/vcpkg &&
            /tmp/vcpkg/bootstrap-vcpkg.sh &&
            /tmp/vcpkg/vcpkg install ompl octomap pybind11 &&
            export CMAKE_TOOLCHAIN_FILE=/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake &&
            export VCPKG_ROOT=/tmp/vcpkg &&
            export CMAKE_PREFIX_PATH="/tmp/vcpkg/installed/x64-linux/debug;/tmp/vcpkg/installed/x64-linux/release:${CMAKE_PREFIX_PATH}" 

        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - name: List built wheels
        run: ls -l wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4.3.6
        with:
          name: wheels
          path: wheelhouse/*.whl
